### ISSUE TITLE
pronto-inspec gem upload to rubygems.org is needed.

### ISSUE THREAD

**Issue by pauliusm** [stiller-leser/pronto-inspec#1]
It would be very useful to use `gem 'pronto-inspec'` in any project gemfile.
To achieve this, pronto-inspec gem must be uploaded to rubygems.org.

If maintainer is busy, I can take care of it.

**Comment by stiller-leser** [comment]
Sorry, just saw this now. Feel free to upload it to rubygems.org - probably will have a hard time maintaining it in the near future.

**Comment by pauliusm** [comment]
Done - published to rubygems.org

**Comment by stiller-leser** [comment]
Thank you, very much appreciated!

**Comment by pauliusm** [comment]
You're wellcome.
When you release new version, just mention @pauliusm and I will take care of gem.
